import LeanAssumptions
import LeanAssumptionsTest.TestUtil

/-!
Public-surface inventory emitter for coverage-ledger validation.

Building this module during `lake test` writes the current public declaration
surface of the `LeanAssumptions` library to
`.lake/build/lean-assumptions-test/public-surface.txt`, one
`<file>|<declaration>` line per public declaration, sorted. The coverage-ledger
validator diffs that inventory against `schema/coverage-ledger.json`, so a new
public definition cannot land without a ledger entry and a stale ledger entry
cannot survive a rename.

Inventory scope: declarations from `LeanAssumptions.*` modules, excluding
private declarations, internal details, constructors, recursors, generated
structure projections, and instances. Test modules and `Examples/` are outside
the inventory scope.
-/

open Lean Elab Command

namespace LeanAssumptionsTest.Coverage

/-- Auxiliary declaration suffixes generated by Lean rather than written by hand. -/
private def generatedSuffixes : List String :=
  ["rec", "recOn", "casesOn", "brecOn", "below", "ibelow", "binductionOn",
   "noConfusion", "noConfusionType", "ctorElim", "ctorElimType", "ctorIdx",
   "elim", "inj", "injEq", "mk", "ofNat", "ofNat_ctorIdx", "toNat", "sizeOf_spec"]

/-- Strip a trailing `_<digits>` disambiguator from a name component. -/
private def stripNumericSuffix (component : String) : String :=
  match component.splitOn "_" with
  | [] => component
  | parts =>
    match parts.getLast? with
    | some last =>
      if !last.isEmpty && last.all Char.isDigit && parts.length > 1 then
        String.intercalate "_" (parts.dropLast)
      else
        component
    | none => component

/-- Return `true` when a declaration belongs to the public inventory surface. -/
private def isInventoryDeclaration (env : Environment) (declName : Lean.Name)
    (info : ConstantInfo) : Bool :=
  if Lean.isPrivateName declName then false
  else if declName.isInternalDetail then false
  else
    match info with
    | .ctorInfo _ | .recInfo _ => false
    | _ =>
      if (env.getProjectionFnInfo? declName).isSome then false
      else
        match declName with
        | .str _ suffix => !(generatedSuffixes.contains (stripNumericSuffix suffix))
        | _ => true

/-- Return `true` when the declaration or any parent namespace is an instance. -/
private def underInstance : Lean.Name → Lean.Elab.TermElabM Bool
  | .anonymous => pure false
  | name@(.str parent _) => do
    if ← Lean.Meta.isInstance name then
      pure true
    else
      underInstance parent
  | name@(.num parent _) => do
    if ← Lean.Meta.isInstance name then
      pure true
    else
      underInstance parent

/-- Convert a module name into its repository-relative source path. -/
private def moduleToPath (moduleName : Lean.Name) : String :=
  moduleName.toString.replace "." "/" ++ ".lean"

/-- Collect the sorted `<file>|<declaration>` inventory lines. -/
def collectInventory : CommandElabM (Array String) := do
  let env ← getEnv
  let mut lines : Array String := #[]
  for (declName, info) in env.constants.toList do
    let some moduleIdx := env.getModuleIdxFor? declName | continue
    let some moduleName := env.header.moduleNames[moduleIdx.toNat]? | continue
    unless moduleName.getRoot == `LeanAssumptions do continue
    unless isInventoryDeclaration env declName info do continue
    if ← liftTermElabM (underInstance declName) then continue
    -- Generated auxiliaries (casesOn, ctorIdx, mk.inj, ofNat, ...) carry no
    -- source declaration range; hand-written declarations always do.
    if (← Lean.findDeclarationRanges? declName).isNone then continue
    lines := lines.push s!"{moduleToPath moduleName}|{declName}"
  pure (lines.qsort (· < ·))

-- Emit the inventory file consumed by `scripts/check_coverage_ledger.py`.
run_cmd do
  let lines ← collectInventory
  LeanAssumptionsTest.assertTrue "public surface inventory is nonempty" (!lines.isEmpty)
  IO.FS.createDirAll ".lake/build/lean-assumptions-test"
  IO.FS.writeFile ".lake/build/lean-assumptions-test/public-surface.txt"
    (String.intercalate "\n" lines.toList ++ "\n")

end LeanAssumptionsTest.Coverage
